[package]
name = "send-tx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
ethers = "2.0"
log = "0.4.22"
thiserror = "2.0.6"
tokio = { version = "1", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
] }
